In [1]:
%load_ext autoreload
%autoreload 2
import sys, os
from os.path import expanduser
## actions required!!!!!!!!!!!!!!!!!!!! change your folder path 
path = "~/Documents/G3/MA-prediction"
path = expanduser(path)
sys.path.append(path)

import pandas as pd
import numpy as np

pd.options.mode.chained_assignment = None
import warnings
warnings.simplefilter(action='ignore', category=pd.errors.PerformanceWarning)
warnings.simplefilter(action='ignore', category=FutureWarning)

In [2]:
from MA_prediction.utils import *
from MA_prediction.preprocessing import *
from MA_prediction.crsp import *
from MA_prediction.mkt_calendar import *
from sklearn.utils import _is_arraylike_not_scalar

In [3]:
mkt_data_tgt_processed, mkt_data_acq_processed = load_mkt_data(path, "processed")

In [9]:
x = mkt_data_acq_processed.map(lambda x: x.prc.isna().sum(), na_action="ignore").fillna(0)

In [12]:
y = mkt_data_acq_processed.map(lambda x: len(np.unique(x.cfacpr)), na_action="ignore").fillna(1)

In [15]:
y[y>1]

master_deal_no
22702020      2.0
108078020     2.0
19696020      2.0
25868020      2.0
25507020      2.0
             ...
3353103020    2.0
3689618020    2.0
3734977020    2.0
3816728020    2.0
3950947020    2.0
Length: 620, dtype: float64

In [20]:
mkt_data_acq_processed[3689618020]

,permno,prc,ret,vol,shrout,cfacpr,cfacshr,mktcap,mktcap_prev,prc_adj,prc_adj_prev
date,,,,,,,,,,,
2020-11-19,16393.0,0.8954,-0.048661,101987.0,7771.0,0.006667,0.006667,6958.153304,NaN,0.895400,NaN
2020-11-20,16393.0,0.9013,0.006589,46974.0,7771.0,0.006667,0.006667,7004.002402,6958.153304,0.901300,0.895400
2020-11-23,16393.0,0.8954,-0.006546,66775.0,7771.0,0.006667,0.006667,6958.153304,7004.002402,0.895400,0.901300
2020-11-24,16393.0,0.8865,-0.009940,51639.0,7771.0,0.006667,0.006667,6888.991507,6958.153304,0.886500,0.895400
2020-11-25,16393.0,0.8493,-0.041963,111050.0,7771.0,0.006667,0.006667,6599.910509,6888.991507,0.849300,0.886500
...,...,...,...,...,...,...,...,...,...,...,...
2021-08-05,16393.0,3.8600,0.072222,6130601.0,15842.0,0.020000,0.020000,61150.118338,57031.198489,1.286731,1.200060
2021-08-06,16393.0,3.6500,-0.054404,1533176.0,15842.0,0.020000,0.020000,57823.301511,61150.118338,1.216728,1.286731
2021-08-09,16393.0,3.6700,0.005479,1344658.0,15842.0,0.020000,0.020000,58140.141209,57823.301511,1.223395,1.216728
2021-08-10,16393.0,3.5200,-0.040872,1570660.0,15842.0,0.020000,0.020000,55763.839698,58140.141209,1.173392,1.223395
2021-08-11,16393.0,3.4000,-0.034091,1256347.0,15842.0,0.020000,0.020000,53862.801511,55763.839698,1.133390,1.173392

In [3]:
import wrds
db = wrds.Connection()

Enter your WRDS username [yizhan]: olivershu
Enter your password: Â·Â·Â·Â·Â·Â·Â·Â·

WRDS recommends setting up a .pgpass file.

Create .pgpass file now [y/n]?:  y

Created .pgpass file successfully.
Loading library list...
Done

In [4]:
get_stock_market_data_daily_CRSP('AMZN', "ticker", db=db)

,permno,prc,ret,vol,shrout,cfacpr,cfacshr
date,,,,,,,
1997-05-15,84788.0,23.500000,NaN,6029815.0,23859.0,240.0,240.0
1997-05-16,84788.0,20.750000,-0.117021,1232226.0,23859.0,240.0,240.0
1997-05-19,84788.0,20.500000,-0.012048,512070.0,23859.0,240.0,240.0
1997-05-20,84788.0,19.625000,-0.042683,456357.0,23859.0,240.0,240.0
1997-05-21,84788.0,17.125000,-0.127389,1577414.0,23859.0,240.0,240.0
...,...,...,...,...,...,...,...
2022-12-23,84788.0,85.250000,0.017425,57376887.0,10201654.0,1.0,1.0
2022-12-27,84788.0,83.040001,-0.025924,57308663.0,10201654.0,1.0,1.0
2022-12-28,84788.0,81.820000,-0.014692,58158484.0,10201654.0,1.0,1.0
2022-12-29,84788.0,84.180000,0.028844,54930062.0,10201654.0,1.0,1.0
2022-12-30,84788.0,84.000000,-0.002138,62295950.0,10201654.0,1.0,1.0

In [4]:
get_stocknames_CRSP(79129.0, db=db)

,permno,permco,ticker,comnam,namedt,nameenddt,cusip,ncusip
0,79129.0,29807.0,GGP,GENERAL GROWTH PROPERTIES INC,1993-04-08,2009-04-15,11282X10,37002110
1,79129.0,29807.0,None,GENERAL GROWTH PROPERTIES INC,2009-04-16,2010-03-04,11282X10,37002110
2,79129.0,29807.0,GGP,GENERAL GROWTH PROPERTIES INC,2010-03-05,2010-11-09,11282X10,37002110
3,79129.0,29807.0,GGP,GENERAL GROWTH PPTYS INC NEW,2010-11-10,2017-01-26,11282X10,37002310
4,79129.0,29807.0,GGP,G G P INC,2017-01-27,2018-08-27,11282X10,36174X10
5,79129.0,29807.0,BPR,BROOKFIELD PROPERTY REIT INC,2018-08-28,2020-03-01,11282X10,11282X10
6,79129.0,29807.0,BPYU,BROOKFIELD PROPERTY REIT INC,2020-03-02,2021-07-26,11282X10,11282X10

In [6]:
get_stocknames_CRSP(87797.0, db=db)

,permno,permco,ticker,comnam,namedt,nameenddt,cusip,ncusip
0,87797.0,18329.0,ONVI,ONVIA COM INC,2000-03-01,2000-07-31,68338T40,68338T10
1,87797.0,18329.0,ONVI,ONVIA COM INC,2000-08-01,2002-06-02,68338T40,68338T10
2,87797.0,18329.0,ONVI,ONVIA COM INC,2002-06-03,2002-07-16,68338T40,68338T10
3,87797.0,18329.0,ONVI,ONVIA COM INC,2002-07-17,2004-06-29,68338T40,68338T40
4,87797.0,18329.0,ONVI,ONVIA INC,2004-06-30,2017-11-16,68338T40,68338T40

In [5]:
get_stocknames_CRSP("BPR", "ticker", db=db)

,permno,permco,ticker,comnam,namedt,nameenddt,cusip,ncusip
0,79129.0,29807.0,BPR,BROOKFIELD PROPERTY REIT INC,2018-08-28,2020-03-01,11282X10,11282X10